{
 "title": "EVS Statistics",
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  { "title": "Daily statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Balances",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  DATE(created_at) AS \"time\",\n  COUNT(1) AS value\nFROM balance\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "Notifications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  DATE(created_at) AS time,\n  COUNT(1)\nFROM\n  notification\nGROUP BY 1\n"
    }
   ]
  },
  {
   "title": "New users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 10 },
   "targets": [
    {
     "rawSql": "WITH all_dates AS (\n  SELECT\n    t.day::date AS time\n  FROM\n    generate_series(\n      (SELECT MIN(created_at) FROM account),\n      (SELECT current_date),\n      INTERVAL '1' DAY\n    ) AS t(day)\n)\n\nSELECT\n  all_dates.time\n  , COUNT(account.username)\nFROM\n  account\nRIGHT JOIN\n  all_dates ON (all_dates.time = DATE(account.created_at))\nGROUP BY 1"
    }
   ]
  },
  { "title": "Lifetime statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Active users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT username) FROM subscription;"
    }
   ]
  },
  {
   "title": "Accounts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT COUNT(1) FROM account;" }
   ]
  },
  {
   "title": "Balances",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT COUNT(1) FROM balance;" }
   ]
  },
  {
   "title": "Notifications",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(1) FROM notification;"
    }
   ]
  }
 ]
}